### ISSUE TITLE
`app.config` improvements

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#14670]
Following up nuxt/nuxt.js#14330 (editable `app.config`), notes in initial implementation nuxt/framework#6333 and ideas from @Tahul in #6779, i've created this issue to track some potential improvements before releasing this new feature in next RC. (currently support is available on edge. Docs: https://v3.nuxtjs.org/guide/features/app-config)

- [x] Initial support (#6136)
- [x] Support HMR after destructing objects with deep assignment (#6788)
- [x] Use `defu. defuFn ` to allow _overrriding_ arrays in multi-layer format (#6905)
- [x] Support `updateAppConfig` with deep assignment (#6905)
- [x] Support `app.config` for server (https://github.com/nuxt/nuxt/pull/19489)
- [ ] ~~Allow multiple named exports from `app.config` (@Atinux idea)~~ (canceled because `defineAppConfig` type benefits will be lost this way)

--- 

Resources:

- Example for custom app configs: https://stackblitz.com/edit/github-al5fwp?file=module.ts,app.vue,custom.config.ts

**Comment by terwer** [comment]
This seems to be not resolved.
Nuxt 3.4.1 still have the problem

![image](https://user-images.githubusercontent.com/3259282/232949424-95c266a0-c898-4bae-ac27-0ea68b6bb0be.png)

**Comment by danielroe** [comment]
@terwer Would you open a new issue with a reproduction? 🙏

**Comment by terwer** [comment]
> @terwer Would you open a new issue with a reproduction? 🙏

@danielroe Thanks for your reply.

After a rebuild and add to tsconfig.json

```
{
  // https://nuxt.com/docs/guide/concepts/typescript
  "extends": "./.nuxt/tsconfig.json"
}
```

Now it seems works,not report error now.below is the generated `app.config.d.ts`

```

import type { CustomAppConfig } from 'nuxt/schema'
import type { Defu } from 'defu'
import cfg0 from "/Users/terwer/Documents/mydocs/zhi/apps/zhi-web-blog/app.config"

declare const inlineConfig = {}
type ResolvedAppConfig = Defu<typeof inlineConfig, [typeof cfg0]>
type IsAny<T> = 0 extends 1 & T ? true : false

type MergedAppConfig<Resolved extends Record<string, any>, Custom extends Record<string, any>> = {
  [K in keyof Resolved]: K extends keyof Custom
    ? IsAny<Custom[K]> extends true
      ? Resolved[K]
      : Custom[K] extends Record<string, any>
        ? Resolved[K] extends Record<string, any>
          ? MergedAppConfig<Resolved[K], Custom[K]>
          : Exclude<Custom[K], undefined>
        : Exclude<Custom[K], undefined>
    : Resolved[K]
}

declare module 'nuxt/schema' {
  interface AppConfig extends MergedAppConfig<ResolvedAppConfig, CustomAppConfig> { }
}
declare module '@nuxt/schema' {
  interface AppConfig extends MergedAppConfig<ResolvedAppConfig, CustomAppConfig> { }
}

```

with the `cfg0` import, it likes it will well recongnize the type.
Thakns.If it occurs in the future, I will back and open a new issue.
