### ISSUE TITLE
server component roadmap

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxt#19772]
We have experimental support in Nuxt 3 for both island components and server-only components (which are implemented using islands) - see https://github.com/nuxt/framework/pull/5689 and https://github.com/nuxt/framework/pull/9972 for initial implementations and https://github.com/nuxt/nuxt/discussions/17956 for initial partial RFC.

There are a number of future linked improvements. This issue is to track those and provide some place to document the linking story, purpose and usage of server components within Nuxt.

## Purpose and usage

Currently we are collecting use patterns to ensure that the final API and implementation for server components is useful. But the following are some benefits we are exploring:

1. security and direct access to server APIs within certain components
2. separate caching strategies for individual chunks of HTML
3. leaner bundle size (keeping some dependencies solely on the server, e.g. syntax highlighting)
4. extensibility
5. rendering individual components within other modules or server routes (e.g. for component previews, OG images, PDF downloads, etc.)
6. ...

Comments and suggestions are very welcome.

```[tasklist]
### Roadmap
- [ ] Allow async components - https://github.com/nuxt/nuxt/issues/18500
- [ ] Client-side interactivity - https://github.com/nuxt/nuxt/issues/19765
- [ ] Hybrid/remote/streaming sources for server components - https://github.com/nuxt/nuxt/issues/12343
```

**Comment by Twitch0125** [comment]
I think it'd make sense to have all the available auto imports for server route handlers be available for server components.

**Comment by Hebilicious** [comment]
This looks promising. Here's my personal 2 cents for "server components".

_Disclaimer: I think this name in general is extremely confusing, due to the fact that it's already complicated to understand what's going on. This is not really a problem related to Nuxt, but React has the same problem with RSC, where most people don't really know how they differ from SSR components... Anyways here is some [reading](https://www.plasmic.app/blog/how-react-server-components-work) to get up to speed ... ._

## 1) More Unified Rendering API

Right now here's a recap of what is possible (correct me if I'm wrong) :

- Nitro [route rules](https://nitro.unjs.io/guide/routing) : It is possible to decide where and how a *page* will be rendered. This also allows the handling of more things, like caching rules, redirect, headers ... 
  - This works at the page level through a config file
  - This allows patterns like SPA/SSG/SSR/SSR+SWR
  
- Nuxt [Server components](https://nuxt.com/docs/guide/directory-structure/components#server-components) : It is possible to tag a *component* as server only by using `.server.vue`. This disable hydration and achieve the same thing as SSG.
  - Works at the component level through the file name
  - This allows pattern like "0 javascript" components.

- Nuxt [Client components](https://nuxt.com/docs/guide/directory-structure/components#clientonly-component) : This is a vue component that can be used to disable SSR at the *component* level, using a wrapper component.
  - Works at the component level through a wrapper component
  - This allows patterns like "Javascript only" rendering.

As we had more and more features and new things, this becomes hard to understand what takes priority and how everything works. I'm not sure what would be a good way to unify everything. That being said, given that routes and pages are also components, I would personally like to have a good granular API that works for both: 

```vue
// This could be "aliased" to nuxt="server" and further down to "nuxt-server"
<script setup nuxt="{ render: 'server', hydrate: false }">
console.log("This will be logged on the server only")
</script>
<template>Server Only</template>
```

```vue
// This could be "aliased" to nuxt="client" and further down "nuxt-client"
<script setup nuxt="{ render: 'client' }">
console.log("This will be logged on the client only")
</script>
<template>Client Only</template>
```

This would be compatible with the "naming" api, ie, renaming a file to `.server.vue` would effectively do the same as using the nuxt="server" script tag. `<ClientOnly />` could be deprecated and replaced by `.client.vue`. 

There could be a configuration file/hook to define custom rendering "templates" so they can be re-used easily (like nuxt="server" => nuxt="{ render:'server', hydrate: false}"). 

If I'm not mistaken the default for all components and pages should be nuxt="{ render:'server', hydrate: 'true' }" and therefore can be omitted. There should be an easy way to change this default, to enable full SPA or SSG by default. 

This is meant to work in tandem with Nitro and these should be "merged" with route rules (the same keys can be used in both route rules and here to unify the API). Some kind of human-readable auto-generated artifact (`nuxt-rendered.json` ?) should be generated, representing the component tree, so there's a source of truth of what's going on. This can be used by VSCode extensions and the likes for more advanced use case, such as displaying a different file icon for server/client components...

We can detect the "invalid" configurations (ie render: "client" + prerender: "true" or hydrate: "true") and emit a warning.

### Alternative API

A few other alternatives API are worth suggesting :

```vue
//could be nuxt-render etc
<render>
export { render: 'server', hydrate: false, prerender: true }
</render>
<script setup>console.log("full static")</script>
```

```vue
<script setup>
useNuxtRender(() => ({render: "server", hydrate: "false"}))
console.log("server Only")
</script>
```

## 2) Streaming

I know that there's some plans regarding streaming, and I wrote this in [another issue](https://github.com/nuxt/nuxt/issues/4753#issuecomment-1502117379), so I'm not sure what applies here : Now that Lambda supports streaming, as well as Cloudflare Workers, how does this relate to Server Component streaming ? What I would assume is that if we have some kind of nested layout like this : 

```
+------+------------------------------------+
| Index                                     |
|      +------+-----------------------------+
|      | SSG                                |
|      |      +------+----------------------+
|      |      | ServerOnly                  |
|      |      +-----------------------------+
|      +------------------------------------+
+------+------------------------------------+
```
Here Nuxt should start streaming HTML (using vue pipeToWebWritable instead of renderToString), first what's already present on the server (static layouts, pre-rendered pages/components), then render the ServerOnly components and pass that to the stream. 
Now I don't know if this important / needed for the Streaming source of the server components.
What I do know is that the Root component needs to be a "server component", and that server components should support slots for both client and server components.

**Comment by HendrikJan** [comment]
I'm probably a bit lat at this party, but I've got an alternative to `.server` components that has slightly different but mostly the same benefits: #20802

**Comment by cosbgn** [comment]
I agree with @HendrikJan - His solution would be ideal for my use case. My main issue with `component.server.vue` is that I would still need multiple files, I would need a billing.vue page and a billing.server components, which doesn't change much from having a billing.js endpoint, I would still have 2 files to manage my billing. 

Ideally I want one billing.vue page where I have all my billing logic, frontend and backed. 
I have so many file-x.vue for frontend and file-x.js for backend - I would really love to unify them in one single file.

**Comment by Hebilicious** [comment]
> I agree with @HendrikJan - His solution would be ideal for my use case. My main issue with `component.server.vue` is that I would still need multiple files, I would need a billing.vue page and a billing.server components, which doesn't change much from having a billing.js endpoint, I would still have 2 files to manage my billing.
> 
> Ideally I want one billing.vue page where I have all my billing logic, frontend and backed. I have so many file-x.vue for frontend and file-x.js for backend - I would really love to unify them in one single file.

What you are both discussing is another feature that is quite different from server components. 
A <server> SFC block or something like this can be implemented without too much effort (I think): 

```html
//page/todos.vue
<server>
export default defineEventHandler(() => {
	return [{id: 1, description: "hello-world"}]
})
</server>
<script setup>
const { data } = useFetch("/todos")
console.log(data) // [{id: 1, description: "hello-world"}]
</script>
```
What would happen is that the server block content would be added as route handler in /api/todos.ts.
I've been thinking about doing something like this with a nuxt module... If enough people are interested I might just move forward with it.

**Comment by cosbgn** [comment]
>  I've been thinking about doing something like this with a nuxt module... If enough people are interested I might just move forward with it.


As a module it would be amazing and I think the implementation is great (using fetch) and keeping it as a backend function

**Comment by urbgimtam** [comment]
I've been trying out Nuxt Server Components and really enjoyed the experience! 

But I have a few questions that I consider interesting:

- If there was a way for Nuxt to automatically detect if a component can be upgraded into a server component (ie: doesn't have interactivity, etc), wouldn't it be interesting to apply this detection and conversion all over the Nuxt app? What would be its pros and cons?

- The usage of Server Components can improve interaction responsiveness due to less hydration and less js to be downloaded to the client. But at the extreme, wouldn't the server CPU become taxed, building all the HTML to ship to the client? Would a caching system for Server Components bring benefits, and how could that work?

**Comment by jd-solanki** [comment]
> If there was a way for Nuxt to automatically detect if a component can be upgraded into a server component (ie: doesn't have interactivity, etc), wouldn't it be interesting to apply this detection and conversion all over the Nuxt app? What would be its pros and cons?

I really liked this, In addition to this, I also like to ask will it be possible to identify if the component is rendered on server or on the client because when me react colleagues ask my help on server component first time I wonder about is "how do you identify if that component loaded on sever or client". The point is, for beginner to server side components it might be the nightmare.

**Comment by MuhammadKhizar7** [comment]
> * The usage of Server Components can improve interaction responsiveness due to less hydration and less js to be downloaded to the client. But at the extreme, wouldn't the server CPU become taxed, building all the HTML to ship to the client? Would a caching system for Server Components bring benefits, and how could that work?

I also discussed the same thing before in a discussion https://github.com/nuxt/nuxt/discussions/16469. I think server components and caching go hand in hand (just like React does). Otherwise, what would be the difference between Nuxt and PHP or ASP.NET Razor pages (they also have page caching)? With server components and on edge (Vercel, Cloudflare Worker), there is a cost and time delay (like 10 API calls) every time this page renders, just like in server-side PHP, etc.

I am proposing component caching along with the current page-level caching. Some components change often, while others do not. Why not cache these components instead of the page? Or, if they never change, make them static?

**Comment by Rigo-m** [comment]
From a team-oriented standpoint, is it feasible to add an option to the nuxt.config so that by default every component is a server component and client hydration is opt-in?
This would help with streamlining development so that the approach for the whole team is to work in a client-performance, small client bundle environment and thoroughly think through the addition of client side javascript.
I don't know if I conveyed my thoughts correctly on this one.
Let me know.

**Comment by madebyfabian** [comment]
Hi there! I just discovered something currently not implemented that could be interesting:

When using `throw createError({ statusCode: 404 })` in a server component, I expect nuxt to transfer the error to the client and display an error page. Just like it's advised to do so in regular components at https://nuxt.com/docs/getting-started/error-handling#example-1.

When I try to do that with a server component, the follow happens:

1. The HTTP Request to this component (`/__nuxt_island/`) returns a clean http 404. That's kind of good.
2. But then I get a log from vue-router, complaining the route doesn't exist:
    ```bash
    [Vue Router warn]: No match found for location with path "/__nuxt_island/MyComponent_KtzRNsoXNj"
    ```
3. And the rendered page on the client doesn't show any signs of an error. Just a blank page. 

Is there a way to catch these so that I get the `error.vue` template displayed, and nuxt catching that error?

**Comment by Youhan** [comment]
Would there be a way to serve a server component using nuxt and then consume it using vanilla JS on other apps?

**Comment by fabianwohlfart** [comment]
Is there a way to not run into `431` header issues when using server components, for example for long texts passed as props to a markdown component, despite changing the server settings `max-http-header-size`?

**Comment by kingyue737** [comment]
Is there a way to know when `NuxtIsland` succeeded in fetching the new island? I want to implement a loading overlay that only shows during fetching new island triggered by props change.

Currently, we have the [`error` event](https://nuxt.com/docs/api/components/nuxt-island#events) to know when the fetch fails. Maybe we can add a `success` event?

**Comment by Rigo-m** [comment]
> Is there a way to know when `NuxtIsland` succeeded in fetching the new island? I want to implement a loading overlay that only shows during fetching new island triggered by props change.
> 
> Currently, we have the [`error` event](https://nuxt.com/docs/api/components/nuxt-island#events) to know when the fetch fails. Maybe we can add a `success` event?

And, by the same logic, a progress event

**Comment by johnjenkins** [comment]
Just chiming in to add a '+1' to some kind of caching for server components; we've recently had our first foray into using them and whilst in-isolation 'lighthouse number go up' their introduction has also made general server response time go up.

e.g. June 21st is when we merged in our first, server-component POC (a `Markdown.server.vue` component as outlined in most demos)
![image](https://github.com/user-attachments/assets/8405a986-dce5-4354-b1cd-22d2de0e2f85)

**Comment by danielroe** [comment]
@johnjenkins exactly!

It might be worth adding a shortcut for doing that in Nuxt to avoid dependency on Nuxt internals.

**Comment by danielroe** [comment]
@gaisinskii You should be able to import them from `#component`.

**Comment by gaisinskii** [comment]
@danielroe Thanks for taking your time and replying to me. I've tried to replace

`import AppTitle from '@/components/AppTitle/AppTitle.server.vue';`

with

`import { AppTitle } from '#components';` or `import AppTitle from '#components';`

but doesn't work, i get this error

<img width="669" alt="Screenshot 2024-08-14 at 18 02 50" src="https://github.com/user-attachments/assets/5cb61982-6da1-4b72-88cc-0a309f62a6a9">


Here is the updated stackblitz https://stackblitz.com/edit/nuxt-starter-ynsx3b?file=app.vue

**Comment by oumarbarry** [comment]
you should try:

`import { AppTitleServer } from '#components'`

**Comment by Dante-dan** [comment]
As your stackblitz: you set the `components` to `empty dirs`, you can read [this doc for components config](https://nuxt.com/docs/api/nuxt-config#components)

You set the`componentIslands: true` so you can use only server component, you should use `import { AppTitle } from '#components'`.

Please check this link: https://stackblitz.com/edit/nuxt-starter-wtmrvq?file=app.vue,nuxt.config.ts

**Comment by bernhardberger** [comment]
Is there any chance to make server components / islands work with SWR rendering? 

I'm a big fan of the SWR mode, which imho is an absolute killer feature of Nuxt but being unable to use server components with it (they simply don't render and are emtpy) is a huge setback when having lots of components that don't need hydration and it pollutes the client bundle with stuff that doesn't need to be there. 

Lazy hydration does help somewhat with the Lighthouse score, but the stuff still ends up in the client bundle.

I know there were a few issues about this somewhere, but none of them is linked to here, and I can't seem to find them anymore. I also don't see that issue being mentioned on the roadmap, although it is a really big one, imho.

**Comment by fabianwohlfart** [comment]
@bernhardberger If you have a problem with a feature best is to open up a new issue with a minimal reproduction of your error, in that way the nuxt team has it a better overview.

**Comment by bernhardberger** [comment]
@fabianwohlfart reproduction can be found here: https://github.com/nuxt/nuxt/issues/24088

**Comment by jd-solanki** [comment]
Is it possible for linters like eslint to identify if the component is interactive or not and based on that they suggest that we should convert this to server component and vice versa?

**Comment by alapeta** [comment]
Is this possible to use Reducer/Reviver for types passed as data to client slot (from server island to client on slot)?
I can't make it work. 
Reducer is apparently called on data, but it seems that its output is ignored as Reviver is not called on client side and data are passed unchanged...

**Comment by danielroe** [comment]
reducer/revivers are only for data in the nuxt payload.

**Comment by Hebilicious** [comment]
@danielroe On a related note, it might be a good idea to consider alternative names for this feature. It would help to promote the concept without having it being associated by default with RSC due to their names being the same, or having to explain the difference. 

How about Nuxt Server Islands ? That way it's crystal clear that it its own novel concept, but it's still reminiscent of both RSC and Island architecture, like mentioned in your blog post.

**Comment by remihuigen** [comment]
> Is there a way to not run into `431` header issues when using server components, for example for long texts passed as props to a markdown component, despite changing the server settings `max-http-header-size`?

I've encountered this issue while implementing a server component for rendering Tiptap content. Since the content is static and doesn't require client-side interactivity, using a server component would be ideal, allowing me to offload rendering from the client and reduce bundle size.

However, because the entire page content is serialized into the request headers as props, this approach consistently exceeds header size limits, making it unviable. Are there established best practices or alternative patterns to handle large payloads efficiently in this context?
