### ISSUE TITLE
OpenSSF Scorecard checklist

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxt#21322]
As part of improving Nuxt's security profile, I'm working through implementing recommendations from the [OSSF Scorecard](https://github.com/ossf/scorecard). While not all of them will be relevant for Nuxt, I still think there are some best practices we can implement.

```[tasklist]
### Tasks
- [x] **CI-Tests**: 26 out of 26 merged PRs checked by a CI test -- score normalized to 10 - [more info](https://github.com/ossf/scorecard/blob/dc7350546ebb66049d82fdad60593bcb56620b06/docs/checks.md#ci-tests)
- [x] **Contributors**: 72 different organizations found -- score normalized to 10  - [more info](https://github.com/ossf/scorecard/blob/dc7350546ebb66049d82fdad60593bcb56620b06/docs/checks.md#contributors)
- [x] **Dangerous-Workflow**: no dangerous workflow patterns detected - [more info](https://github.com/ossf/scorecard/blob/dc7350546ebb66049d82fdad60593bcb56620b06/docs/checks.md#dangerous-workflow)
- [x] **Dependency-Update-Tool**: update tool detected - [more info](https://github.com/ossf/scorecard/blob/dc7350546ebb66049d82fdad60593bcb56620b06/docs/checks.md#dependency-update-tool)
- [x] **License**: license file detected - [more info](https://github.com/ossf/scorecard/blob/dc7350546ebb66049d82fdad60593bcb56620b06/docs/checks.md#license)
- [x] **Maintained**: 30 commit(s) out of 30 and 23 issue activity out of 30 found in the last 90 days -- score normalized to 10 - [more info](https://github.com/ossf/scorecard/blob/dc7350546ebb66049d82fdad60593bcb56620b06/docs/checks.md#maintained)
- [x] **Packaging**: publishing workflow detected   - [more info](https://github.com/ossf/scorecard/blob/dc7350546ebb66049d82fdad60593bcb56620b06/docs/checks.md#packaging)
- [x] **Security-Policy**: security policy file detected  - [more info](https://github.com/ossf/scorecard/blob/dc7350546ebb66049d82fdad60593bcb56620b06/docs/checks.md#security-policy)
- [x] **Binary-Artifacts**: binaries present in source    code - [more info](https://github.com/ossf/scorecard/blob/dc7350546ebb66049d82fdad60593bcb56620b06/docs/checks.md#binary-artifacts)
- [x] **SAST**: SAST tool is not run on all   commits -- score normalized to 0 - [more info](https://github.com/ossf/scorecard/blob/dc7350546ebb66049d82fdad60593bcb56620b06/docs/checks.md#sast) - https://github.com/nuxt/nuxt/pull/21324
- [ ] **CII-Best-Practices**: ![OpenSSF Best Practices](https://bestpractices.coreinfrastructure.org/projects/7419/badge) - [more info](https://github.com/ossf/scorecard/blob/dc7350546ebb66049d82fdad60593bcb56620b06/docs/checks.md#cii-best-practices)
- [ ] **Vulnerabilities**: 2 existing vulnerabilities    detected - [more info](https://github.com/ossf/scorecard/blob/dc7350546ebb66049d82fdad60593bcb56620b06/docs/checks.md#vulnerabilities): https://github.com/nuxt/nuxt/pull/21326
- [x] **Pinned-Dependencies**: dependency not pinned by hash detected -- score normalized  to 4 - [more info](https://github.com/ossf/scorecard/blob/dc7350546ebb66049d82fdad60593bcb56620b06/docs/checks.md#pinned-dependencies) - https://github.com/nuxt/nuxt/pull/21328
- [ ] **Branch-Protection**: branch protection is not      maximal on development and all release branches - [more info](https://github.com/ossf/scorecard/blob/dc7350546ebb66049d82fdad60593bcb56620b06/docs/checks.md#branch-protection)
- [ ] **Code-Review**: found 8 unreviewed human      changesets (30 total - [more info](https://github.com/ossf/scorecard/blob/dc7350546ebb66049d82fdad60593bcb56620b06/docs/checks.md#code-review))
- [ ] **Fuzzing**: project is not fuzzed - [more info](https://github.com/ossf/scorecard/blob/dc7350546ebb66049d82fdad60593bcb56620b06/docs/checks.md#fuzzing)
- [ ] **Token-Permissions**: non read-only tokens detected in GitHub workflows - [more info](https://github.com/ossf/scorecard/blob/dc7350546ebb66049d82fdad60593bcb56620b06/docs/checks.md#token-permissions) - https://github.com/nuxt/nuxt/pull/21328
- [ ] **Signed-Releases**: no releases found - [more info](https://github.com/ossf/scorecard/blob/dc7350546ebb66049d82fdad60593bcb56620b06/docs/checks.md#signed-releases)
```

**Comment by Hebilicious** [comment]
Great idea ! I would love to have more sensible security defaults out-of-the box. 

A few things that comes to mind : 
- Add a security section to the box
- add an origin check for POST requests and a flag to disable it, similar to [sveltekit](https://kit.svelte.dev/docs/configuration#csrf)
- Add some of the security features provided by nuxt/security in core
