### ISSUE TITLE
Add an `attach` command to nuxi CLI to install modules

### ISSUE THREAD

**Issue by icarusgk** [nuxt/nuxt#21574]
### Describe the feature

![Frame 48 (4)](https://github.com/nuxt/nuxt/assets/38413630/7f188480-cc8c-46f1-aeec-6b7e76955fa3)

This issue proposes the addition of a new command, `nuxi attach`, to the CLI, allowing users to install Nuxt modules and update the `nuxt.config.ts` file accordingly.

Currently, there is no straightforward way to install Nuxt modules and automatically update the `nuxt.config.ts` file with the installed modules. This often requires manual installation and editing of the configuration file.

This would make a fantastic addition to the nuxi CLI! 😄 Both [Qwik](https://qwik.builder.io/docs/integrations/tailwind/) and [Astro](https://docs.astro.build/en/guides/integrations-guide/) have already implemented similar features within their CLIs, which have been highly beneficial to their users.

## Proposed Changes
- Implement the `nuxi attach` command in the CLI.

**Usage**

```bash
nuxi attach <module>
```

- The `nuxi attach` command will take the name of the desired Nuxt module as an argument and install the equivalent package.

**Example**
```bash
# Tailwind
nuxi attach tailwind # Will install @nuxtjs/tailwindcss

# Pinia
nuxi attach pinia # Will install @pinia/nuxt

# Apollo
nuxi attach apollo # Will install @nuxtjs/apollo
```
- It will run the appropriate `npm|pnpm|yarn add` command to install the package as a dev dependency.
- The command will then update the `nuxt.config.ts` file by adding the installed module to the modules array.
- If the modules key is not present in the `defineNuxtConfig()`, it will be added with the installed module as the first entry.

## Expected benefits
1. Simplifies the process of installing Nuxt modules by providing a dedicated command.
2. Automates the update of the `nuxt.config.ts` file, reducing manual editing and potential errors.
3. Improves developer productivity and enhances the overall user experience.

## Tasks
- [x] Implement the nuxi attach command in the CLI.
- [x] Update the `nuxt.config.ts` file with the installed modules.
- [x] Test the functionality of the nuxi attach command with different Nuxt modules.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
This is absolutely on the roadmap. We're currently building a new `nuxi` so we won't move forward with this _here_ until it's made open-source. Will DM you though 😉.
