### ISSUE TITLE
Invalidate payload / cache fetch by time

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#21598]
### Describe the feature

Our page its a dinamic page, frecuently we change prices, descriptions, etc...

We need that the https://nuxt.com/docs/getting-started/data-fetching#network-calls-duplication data fetching cache / payload has been invalidate by time ... like cookies

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).
```[tasklist]
### Tasks
- [ ] https://github.com/nuxt/nuxt/issues/21598
```

**Comment by agracia-foticos** [comment]
Great! waiting for the feature

**Comment by ah-dc** [comment]
I hope there are something like [TanStack Query](https://github.com/tanstack/query) but more official
