### ISSUE TITLE
Accessing rendered HTML in Nuxt hook in order to process and change the order of meta tags in nuxt2

### ISSUE THREAD

**Issue by emechpi** [nuxt/nuxt#25188]
### Describe the feature

I used the ```capo.js``` extension and my website has a critical ordering issue in metatags.
how can I find a way to reorder meta tags based on ```capo.js``` suggestions in nuxt2 SSR?

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

**Comment by emechpi** [comment]
@danielroe 
I appreciate you for following up on this issue and your commitment.
I couldn't find a way to solve it, so I decided to handle it for the new website version, which is based on Nuxt 3.
